import type { NoticeItem, NoticeDetail } from "@/types/notice";
import type { SchoolItem, SchoolDetail, DepartmentItem } from "@/types/school";
import type { StatsOverview } from "@/types/api";
import type { TutorItem, TutorDetail } from "@/types/tutor";
import type { UserProfile, FavoriteItem, UserSettings } from "@/types/user";

// ========== Mock 统计数据 ==========
export const mockStats: StatsOverview = {
  school_count: 39,
  notice_count: 256,
  department_count: 812,
  tutor_count: 1280,
};

// ========== Mock 院校数据 ==========
export const mockSchools: SchoolItem[] = [
  {
    id: 1, name: "北京大学", short_name: "北大", level: "985",
    province: "北京", city: "北京", homepage_url: "https://www.pku.edu.cn",
    department_count: 48, notice_count: 12,
  },
  {
    id: 2, name: "清华大学", short_name: "清华", level: "985",
    province: "北京", city: "北京", homepage_url: "https://www.tsinghua.edu.cn",
    department_count: 52, notice_count: 15,
  },
  {
    id: 3, name: "浙江大学", short_name: "浙大", level: "985",
    province: "浙江", city: "杭州", homepage_url: "https://www.zju.edu.cn",
    department_count: 38, notice_count: 10,
  },
  {
    id: 4, name: "复旦大学", short_name: "复旦", level: "985",
    province: "上海", city: "上海", homepage_url: "https://www.fudan.edu.cn",
    department_count: 35, notice_count: 8,
  },
  {
    id: 5, name: "上海交通大学", short_name: "上交", level: "985",
    province: "上海", city: "上海", homepage_url: "https://www.sjtu.edu.cn",
    department_count: 42, notice_count: 11,
  },
  {
    id: 6, name: "南京大学", short_name: "南大", level: "985",
    province: "江苏", city: "南京", homepage_url: "https://www.nju.edu.cn",
    department_count: 33, notice_count: 9,
  },
  {
    id: 7, name: "中国科学技术大学", short_name: "中科大", level: "985",
    province: "安徽", city: "合肥", homepage_url: "https://www.ustc.edu.cn",
    department_count: 28, notice_count: 7,
  },
  {
    id: 8, name: "哈尔滨工业大学", short_name: "哈工大", level: "985",
    province: "黑龙江", city: "哈尔滨", homepage_url: "https://www.hit.edu.cn",
    department_count: 30, notice_count: 6,
  },
  {
    id: 9, name: "武汉大学", short_name: "武大", level: "985",
    province: "湖北", city: "武汉", homepage_url: "https://www.whu.edu.cn",
    department_count: 36, notice_count: 8,
  },
  {
    id: 10, name: "中山大学", short_name: "中大", level: "985",
    province: "广东", city: "广州", homepage_url: "https://www.sysu.edu.cn",
    department_count: 40, notice_count: 7,
  },
  {
    id: 11, name: "四川大学", short_name: "川大", level: "985",
    province: "四川", city: "成都", homepage_url: "https://www.scu.edu.cn",
    department_count: 35, notice_count: 6,
  },
  {
    id: 12, name: "西安交通大学", short_name: "西交", level: "985",
    province: "陕西", city: "西安", homepage_url: "https://www.xjtu.edu.cn",
    department_count: 32, notice_count: 5,
  },
];

// ========== Mock 通知数据 ==========
export const mockNotices: NoticeItem[] = [
  {
    id: 1,
    title: "2026年计算机科学与技术学院推免夏令营招生通知",
    university_name: "北京大学",
    department_name: "计算机科学与技术学院",
    school_level: "985",
    program_type: "夏令营",
    program_type_key: "summer_camp",
    target_degree: "硕博",
    disciplines: ["计算机科学与技术", "人工智能", "软件工程"],
    quota: "30",
    registration_start: "2026-04-01",
    registration_end: "2026-05-15",
    camp_start: "2026-07-01",
    camp_end: "2026-07-05",
    publish_date: "2026-03-20",
    status: "registering",
    summary: "北京大学计算机学院2026年推免夏令营面向全国重点高校招收优秀本科生，涵盖计算机科学、人工智能、软件工程等方向。",
    province: "北京",
    city: "北京",
    tags: ["夏令营", "2026"],
    view_count: 1649,
    intent_count: 43,
    application_rule: "可兼报",
  },
  {
    id: 2,
    title: "2026年电子工程系暑期优秀大学生夏令营",
    university_name: "清华大学",
    department_name: "电子工程系",
    school_level: "985",
    program_type: "夏令营",
    program_type_key: "summer_camp",
    target_degree: "硕博",
    disciplines: ["电子科学与技术", "信息与通信工程"],
    quota: "40",
    registration_start: "2026-04-10",
    registration_end: "2026-05-20",
    camp_start: "2026-07-08",
    camp_end: "2026-07-12",
    publish_date: "2026-03-22",
    status: "registering",
    summary: "清华大学电子工程系2026年暑期夏令营，招收电子信息类优秀本科生。",
    province: "北京",
    city: "北京",
    tags: ["夏令营", "2026"],
    view_count: 892,
    intent_count: 31,
    application_rule: "可兼报",
  },
  {
    id: 3,
    title: "2026年计算机科学与技术学院接收推免研究生预报名通知",
    university_name: "浙江大学",
    department_name: "计算机科学与技术学院",
    school_level: "985",
    program_type: "预推免",
    program_type_key: "pre_admission",
    target_degree: "硕士",
    disciplines: ["计算机科学与技术", "软件工程"],
    quota: "50",
    registration_start: "2026-08-15",
    registration_end: "2026-09-10",
    camp_start: null,
    camp_end: null,
    publish_date: "2026-03-18",
    status: "not_started",
    summary: "浙江大学计算机学院2026年预推免招生，面向全国高校招收推免硕士研究生。",
    province: "浙江",
    city: "杭州",
    tags: ["预推免", "2026"],
    view_count: 567,
    intent_count: 18,
    application_rule: "可兼报",
  },
  {
    id: 4,
    title: "2026年经济学院推免夏令营招生简章",
    university_name: "复旦大学",
    department_name: "经济学院",
    school_level: "985",
    program_type: "夏令营",
    program_type_key: "summer_camp",
    target_degree: "硕士",
    disciplines: ["理论经济学", "应用经济学", "金融学"],
    quota: "25",
    registration_start: "2026-04-05",
    registration_end: "2026-05-10",
    camp_start: "2026-07-03",
    camp_end: "2026-07-06",
    publish_date: "2026-03-15",
    status: "registering",
    summary: "复旦大学经济学院2026年推免夏令营，招收经济学类优秀本科生。",
    province: "上海",
    city: "上海",
    tags: ["夏令营", "2026"],
    view_count: 723,
    intent_count: 25,
    application_rule: "可兼报",
  },
  {
    id: 5,
    title: "2026年数学科学学院直博生招生通知",
    university_name: "北京大学",
    department_name: "数学科学学院",
    school_level: "985",
    program_type: "夏令营",
    program_type_key: "summer_camp",
    target_degree: "博士",
    disciplines: ["基础数学", "应用数学", "统计学"],
    quota: "15",
    registration_start: "2026-04-01",
    registration_end: "2026-04-30",
    camp_start: "2026-06-25",
    camp_end: "2026-06-28",
    publish_date: "2026-03-25",
    status: "registering",
    summary: "北京大学数学科学学院2026年直博生招生，面向全国招收数学类拔尖本科生。",
    province: "北京",
    city: "北京",
    tags: ["夏令营", "科学营", "2026"],
    view_count: 490,
    intent_count: 8,
    application_rule: "可兼报",
  },
  {
    id: 6,
    title: "2026年机械与动力工程学院暑期学术夏令营",
    university_name: "上海交通大学",
    department_name: "机械与动力工程学院",
    school_level: "985",
    program_type: "夏令营",
    program_type_key: "summer_camp",
    target_degree: "硕博",
    disciplines: ["机械工程", "动力工程及工程热物理"],
    quota: "35",
    registration_start: "2026-04-15",
    registration_end: "2026-05-25",
    camp_start: "2026-07-10",
    camp_end: "2026-07-14",
    publish_date: "2026-03-24",
    status: "registering",
    summary: "上海交通大学机械与动力工程学院2026年暑期学术夏令营招生通知。",
    province: "上海",
    city: "上海",
    tags: ["夏令营", "2026"],
    view_count: 345,
    intent_count: 12,
    application_rule: "可兼报",
  },
  {
    id: 7,
    title: "2026年物理学院推免生接收办法",
    university_name: "南京大学",
    department_name: "物理学院",
    school_level: "985",
    program_type: "预推免",
    program_type_key: "pre_admission",
    target_degree: "硕博",
    disciplines: ["物理学", "天文学"],
    quota: "20",
    registration_start: "2026-08-20",
    registration_end: "2026-09-15",
    camp_start: null,
    camp_end: null,
    publish_date: "2026-03-21",
    status: "not_started",
    summary: "南京大学物理学院2026年推免生接收办法，欢迎物理学及相关专业优秀本科生申请。",
    province: "江苏",
    city: "南京",
    tags: ["预推免", "2026"],
    view_count: 289,
    intent_count: 6,
    application_rule: "可兼报",
  },
  {
    id: 8,
    title: "2026年化学与材料科学学院夏令营通知",
    university_name: "中国科学技术大学",
    department_name: "化学与材料科学学院",
    school_level: "985",
    program_type: "夏令营",
    program_type_key: "summer_camp",
    target_degree: "硕博",
    disciplines: ["化学", "材料科学与工程"],
    quota: "30",
    registration_start: "2026-04-08",
    registration_end: "2026-05-08",
    camp_start: "2026-07-05",
    camp_end: "2026-07-09",
    publish_date: "2026-03-19",
    status: "registering",
    summary: "中国科学技术大学化学与材料科学学院2026年暑期夏令营招生。",
    province: "安徽",
    city: "合肥",
    tags: ["夏令营", "2026"],
    view_count: 412,
    intent_count: 15,
    application_rule: "可兼报",
  },
  {
    id: 9,
    title: "经济学理学硕士项目济南、威海、深圳校园宣讲会安排",
    university_name: "香港中文大学（深圳）",
    department_name: "经济管理学院",
    school_level: "other",
    program_type: "宣讲会",
    program_type_key: "seminar",
    target_degree: "硕士",
    disciplines: ["应用经济学", "金融学"],
    quota: null,
    registration_start: "2026-03-24",
    registration_end: "2026-03-31",
    camp_start: "2026-03-25",
    camp_end: "2026-03-31",
    publish_date: "2026-03-23",
    status: "in_progress",
    summary: "招生宣讲会|经济学理学硕士项目济南、威海、深圳校园宣讲会安排",
    province: "广东",
    city: "深圳",
    tags: ["宣讲会", "济南、威海、深圳", "2026"],
    view_count: 417,
    intent_count: 2,
    application_rule: "可兼报",
  },
  {
    id: 10,
    title: `第一届「悟理有术」科学营报名通知`,
    university_name: "中国科学技术大学",
    department_name: "物理学院",
    school_level: "985",
    program_type: "夏令营",
    program_type_key: "summer_camp",
    target_degree: "硕博",
    disciplines: ["物理学"],
    quota: null,
    registration_start: "2026-03-15",
    registration_end: "2026-04-08",
    camp_start: "2026-04-24",
    camp_end: "2026-04-26",
    publish_date: "2026-03-14",
    status: "registering",
    summary: `中国科学技术大学物理学院第一届「悟理有术」科学营报名通知。`,
    province: "安徽",
    city: "合肥",
    tags: ["科学营", "2026"],
    view_count: 1649,
    intent_count: 43,
    application_rule: "可兼报",
  },
  {
    id: 11,
    title: `2026年劳动人事学院第二届「劳人杯」全国劳动经济管理本科生学术论坛`,
    university_name: "中国人民大学",
    department_name: "劳动人事学院",
    school_level: "985",
    program_type: "夏令营",
    program_type_key: "summer_camp",
    target_degree: "硕博",
    disciplines: ["管理学", "经济学"],
    quota: null,
    registration_start: "2026-03-26",
    registration_end: "2026-05-06",
    camp_start: "2026-05-06",
    camp_end: "2026-05-06",
    publish_date: "2026-03-25",
    status: "registering",
    summary: `重磅|第二届「劳人杯」全国劳动经济管理本科生学术论坛报名开启！`,
    province: "北京",
    city: "北京",
    tags: ["学术论坛", "2026"],
    view_count: 420,
    intent_count: 23,
    application_rule: "可兼报",
  },
  {
    id: 12,
    title: "2026内地优秀大学生健康科学夏令营",
    university_name: "澳门大学",
    department_name: "健康科学学院",
    school_level: "other",
    program_type: "夏令营",
    program_type_key: "summer_camp",
    target_degree: "硕博",
    disciplines: ["医学", "生物学"],
    quota: null,
    registration_start: "2026-03-25",
    registration_end: "2026-04-12",
    camp_start: "2026-07-27",
    camp_end: "2026-07-30",
    publish_date: "2026-03-24",
    status: "registering",
    summary: "澳门大学健康科学学院2026内地优秀大学生健康科学夏令营。",
    province: "澳门",
    city: "澳门",
    tags: ["夏令营", "2026"],
    view_count: 490,
    intent_count: 8,
    application_rule: "可兼报",
  },
  {
    id: 13,
    title: "2026年法学院推免夏令营入营名单公示",
    university_name: "武汉大学",
    department_name: "法学院",
    school_level: "985",
    program_type: "入营名单",
    program_type_key: "admission_list",
    target_degree: "硕士",
    disciplines: ["法学"],
    quota: "20",
    registration_start: null,
    registration_end: null,
    camp_start: "2026-07-15",
    camp_end: "2026-07-18",
    publish_date: "2026-03-26",
    status: "in_progress",
    summary: "武汉大学法学院2026年推免夏令营入营名单已公示，请入选同学及时确认。",
    province: "湖北",
    city: "武汉",
    tags: ["入营名单", "2026"],
    view_count: 856,
    intent_count: 0,
    application_rule: "未知",
  },
  {
    id: 14,
    title: "2026年管理学院暑期优秀大学生夏令营",
    university_name: "中山大学",
    department_name: "管理学院",
    school_level: "985",
    program_type: "夏令营",
    program_type_key: "summer_camp",
    target_degree: "硕士",
    disciplines: ["工商管理", "会计学", "市场营销"],
    quota: "40",
    registration_start: "2026-04-20",
    registration_end: "2026-06-01",
    camp_start: "2026-07-15",
    camp_end: "2026-07-18",
    publish_date: "2026-03-26",
    status: "registering",
    summary: "中山大学管理学院2026年暑期优秀大学生夏令营，招收管理学类优秀本科生。",
    province: "广东",
    city: "广州",
    tags: ["夏令营", "2026"],
    view_count: 378,
    intent_count: 14,
    application_rule: "可兼报",
  },
];

// ========== Mock 通知详情 ==========
export const mockNoticeDetail: NoticeDetail = {
  ...mockNotices[0],
  requirements: `1. 全国重点高校（原则上为"双一流"建设高校）本科三年级在读学生（2027年应届毕业生）；
2. 学习成绩优秀，本科前五学期总评成绩排名在本专业前20%；
3. 对计算机科学研究有浓厚兴趣，有较强的科研潜力；
4. 英语水平良好，CET-6成绩425分以上或具有同等水平的英语成绩证明；
5. 身心健康，品行端正。`,
  registration_url: "https://cs.pku.edu.cn/apply",
  official_url: "https://cs.pku.edu.cn/info/1024/3456.htm",
  contact: "联系电话：010-62757801，邮箱：cs-admission@pku.edu.cn",
  raw_content: `北京大学计算机科学与技术学院定于2026年7月1日至7月5日举办"2026年优秀大学生暑期夏令营"活动。

一、招生方向
计算机科学与技术、人工智能、软件工程等方向。

二、申请条件
1. 全国重点高校本科三年级在读学生；
2. 学习成绩优秀，本科前五学期总评成绩排名在本专业前20%；
3. 对计算机科学研究有浓厚兴趣，有较强的科研潜力；
4. 英语水平良好。

三、招生名额
拟招收30人。

四、报名时间
2026年4月1日至2026年5月15日。

五、活动安排
夏令营期间将安排学术讲座、实验室参观、导师面谈、综合面试等环节。

六、联系方式
联系电话：010-62757801
邮箱：cs-admission@pku.edu.cn`,
  source_url: "https://cs.pku.edu.cn/info/1024/3456.htm",
  created_at: "2026-03-20T08:00:00Z",
  prev_year_quota: "50",
};

// ========== Mock 学院数据 ==========
export const mockDepartments: DepartmentItem[] = [
  { id: 1, name: "计算机科学与技术学院", discipline_category: "工学", notice_count: 3, homepage_url: "https://cs.pku.edu.cn" },
  { id: 2, name: "信息科学技术学院", discipline_category: "工学", notice_count: 2, homepage_url: "https://eecs.pku.edu.cn" },
  { id: 3, name: "数学科学学院", discipline_category: "理学", notice_count: 2, homepage_url: "https://math.pku.edu.cn" },
  { id: 4, name: "物理学院", discipline_category: "理学", notice_count: 1, homepage_url: "https://phy.pku.edu.cn" },
  { id: 5, name: "化学与分子工程学院", discipline_category: "理学", notice_count: 1, homepage_url: "https://chem.pku.edu.cn" },
  { id: 6, name: "生命科学学院", discipline_category: "理学", notice_count: 1, homepage_url: "https://bio.pku.edu.cn" },
  { id: 7, name: "经济学院", discipline_category: "经济学", notice_count: 1, homepage_url: "https://econ.pku.edu.cn" },
  { id: 8, name: "光华管理学院", discipline_category: "管理学", notice_count: 1, homepage_url: "https://gsm.pku.edu.cn" },
  { id: 9, name: "法学院", discipline_category: "法学", notice_count: 0, homepage_url: "https://law.pku.edu.cn" },
  { id: 10, name: "外国语学院", discipline_category: "文学", notice_count: 0, homepage_url: "https://sfl.pku.edu.cn" },
];

// ========== Mock 院校详情 ==========
export const mockSchoolDetail: SchoolDetail = {
  ...mockSchools[0],
  graduate_url: "https://grs.pku.edu.cn",
  departments: mockDepartments,
  description: "北京大学创办于1898年，初名京师大学堂，是中国第一所国立综合性大学。北京大学是国家「211工程」和「985工程」首批重点建设的高校之一，也是国家「双一流」建设高校。",
};

// ========== Mock 导师数据 ==========
export const mockTutors: TutorItem[] = [
  {
    id: 1, name: "张三", university_name: "北京大学", department_name: "计算机科学与技术学院",
    school_level: "985", title: "教授/博导", research_areas: ["人工智能", "机器学习", "自然语言处理"],
    homepage_url: "https://cs.pku.edu.cn/info/zhangsan", email: "zhangsan@pku.edu.cn",
    avatar_url: null, province: "北京", city: "北京", discipline: "工学",
    is_recruiting: true, recruiting_info: "每年招收硕士 2-3 名，博士 1-2 名",
    paper_count: 156, project_count: 12, view_count: 2340,
  },
  {
    id: 2, name: "李四", university_name: "清华大学", department_name: "电子工程系",
    school_level: "985", title: "副教授/博导", research_areas: ["计算机视觉", "深度学习", "图像处理"],
    homepage_url: "https://ee.tsinghua.edu.cn/lisi", email: "lisi@tsinghua.edu.cn",
    avatar_url: null, province: "北京", city: "北京", discipline: "工学",
    is_recruiting: true, recruiting_info: "欢迎有数学基础和编程能力的同学申请",
    paper_count: 89, project_count: 8, view_count: 1876,
  },
  {
    id: 3, name: "王五", university_name: "浙江大学", department_name: "计算机科学与技术学院",
    school_level: "985", title: "教授/博导", research_areas: ["数据库系统", "大数据", "分布式计算"],
    homepage_url: "https://cs.zju.edu.cn/wangwu", email: "wangwu@zju.edu.cn",
    avatar_url: null, province: "浙江", city: "杭州", discipline: "工学",
    is_recruiting: true, recruiting_info: "招收对系统研究有兴趣的学生",
    paper_count: 112, project_count: 15, view_count: 1523,
  },
  {
    id: 4, name: "赵六", university_name: "复旦大学", department_name: "经济学院",
    school_level: "985", title: "教授/博导", research_areas: ["宏观经济学", "金融经济学", "计量经济学"],
    homepage_url: "https://econ.fudan.edu.cn/zhaoliu", email: "zhaoliu@fudan.edu.cn",
    avatar_url: null, province: "上海", city: "上海", discipline: "经济学",
    is_recruiting: true, recruiting_info: "招收经济学或数学背景的硕博生",
    paper_count: 78, project_count: 6, view_count: 1245,
  },
  {
    id: 5, name: "孙七", university_name: "上海交通大学", department_name: "机械与动力工程学院",
    school_level: "985", title: "教授/博导", research_areas: ["机器人", "智能制造", "控制工程"],
    homepage_url: "https://me.sjtu.edu.cn/sunqi", email: "sunqi@sjtu.edu.cn",
    avatar_url: null, province: "上海", city: "上海", discipline: "工学",
    is_recruiting: false, recruiting_info: null,
    paper_count: 95, project_count: 10, view_count: 987,
  },
  {
    id: 6, name: "周八", university_name: "南京大学", department_name: "物理学院",
    school_level: "985", title: "教授/博导", research_areas: ["凝聚态物理", "量子计算", "拓扑物理"],
    homepage_url: "https://physics.nju.edu.cn/zhouba", email: "zhouba@nju.edu.cn",
    avatar_url: null, province: "江苏", city: "南京", discipline: "理学",
    is_recruiting: true, recruiting_info: "欢迎物理学和数学专业的同学",
    paper_count: 134, project_count: 9, view_count: 1102,
  },
  {
    id: 7, name: "吴九", university_name: "中国科学技术大学", department_name: "化学与材料科学学院",
    school_level: "985", title: "副教授/硕导", research_areas: ["有机化学", "药物化学", "催化化学"],
    homepage_url: "https://chem.ustc.edu.cn/wujiu", email: "wujiu@ustc.edu.cn",
    avatar_url: null, province: "安徽", city: "合肥", discipline: "理学",
    is_recruiting: true, recruiting_info: "招收化学相关专业硕士生",
    paper_count: 45, project_count: 4, view_count: 678,
  },
  {
    id: 8, name: "郑十", university_name: "哈尔滨工业大学", department_name: "航天学院",
    school_level: "985", title: "教授/博导", research_areas: ["航天器设计", "轨道力学", "空间科学"],
    homepage_url: "https://sa.hit.edu.cn/zhengshi", email: "zhengshi@hit.edu.cn",
    avatar_url: null, province: "黑龙江", city: "哈尔滨", discipline: "工学",
    is_recruiting: true, recruiting_info: "招收航空航天相关专业学生",
    paper_count: 167, project_count: 18, view_count: 1456,
  },
  {
    id: 9, name: "陈十一", university_name: "武汉大学", department_name: "法学院",
    school_level: "985", title: "教授/博导", research_areas: ["民商法", "知识产权法", "国际私法"],
    homepage_url: "https://law.whu.edu.cn/chensy", email: "chensy@whu.edu.cn",
    avatar_url: null, province: "湖北", city: "武汉", discipline: "法学",
    is_recruiting: true, recruiting_info: "招收法学专业硕博生",
    paper_count: 62, project_count: 5, view_count: 834,
  },
  {
    id: 10, name: "林十二", university_name: "中山大学", department_name: "管理学院",
    school_level: "985", title: "副教授/硕导", research_areas: ["市场营销", "消费者行为", "数字营销"],
    homepage_url: "https://bus.sysu.edu.cn/linse", email: "linse@sysu.edu.cn",
    avatar_url: null, province: "广东", city: "广州", discipline: "管理学",
    is_recruiting: true, recruiting_info: "招收管理学或心理学背景的硕士生",
    paper_count: 38, project_count: 3, view_count: 567,
  },
  {
    id: 11, name: "黄十三", university_name: "四川大学", department_name: "华西临床医学院",
    school_level: "985", title: "教授/博导", research_areas: ["肿瘤学", "精准医学", "免疫治疗"],
    homepage_url: "https://wchscu.cn/huangss", email: "huangss@scu.edu.cn",
    avatar_url: null, province: "四川", city: "成都", discipline: "医学",
    is_recruiting: true, recruiting_info: "招收临床医学或生物学背景的博士生",
    paper_count: 203, project_count: 14, view_count: 1890,
  },
  {
    id: 12, name: "杨十四", university_name: "西安交通大学", department_name: "电气工程学院",
    school_level: "985", title: "教授/博导", research_areas: ["电力系统", "新能源", "智能电网"],
    homepage_url: "https://ee.xjtu.edu.cn/yangss", email: "yangss@xjtu.edu.cn",
    avatar_url: null, province: "陕西", city: "西安", discipline: "工学",
    is_recruiting: false, recruiting_info: null,
    paper_count: 145, project_count: 11, view_count: 1234,
  },
];

// ========== Mock 导师详情 ==========
export const mockTutorDetail: TutorDetail = {
  ...mockTutors[0],
  biography: `张三，北京大学计算机科学与技术学院教授、博士生导师。2005年获北京大学计算机科学博士学位，2005-2008年在美国斯坦福大学从事博士后研究。主要研究方向为人工智能、机器学习和自然语言处理。在国际顶级期刊和会议上发表论文150余篇，Google Scholar引用超过8000次。主持国家自然科学基金重点项目、国家重点研发计划等多项科研项目。`,
  education: [
    "2001-2005 北京大学 计算机科学与技术 博士",
    "1997-2001 北京大学 计算机科学与技术 学士",
  ],
  experience: [
    "2015-至今 北京大学计算机科学与技术学院 教授",
    "2008-2015 北京大学计算机科学与技术学院 副教授",
    "2005-2008 斯坦福大学计算机科学系 博士后",
  ],
  publications: [
    "Zhang S, et al. \"Large Language Models for Scientific Discovery.\" Nature Machine Intelligence, 2025.",
    "Zhang S, et al. \"Efficient Transformer Architecture for Long Document Understanding.\" ACL 2024.",
    "Zhang S, et al. \"Self-supervised Learning for Multimodal Representation.\" NeurIPS 2023.",
    "Zhang S, et al. \"Knowledge Graph Enhanced Pre-training.\" AAAI 2023.",
    "Zhang S, et al. \"Neural Architecture Search with Reinforcement Learning.\" ICML 2022.",
  ],
  projects: [
    "国家自然科学基金重点项目：面向开放域的大语言模型关键技术研究（2024-2028）",
    "国家重点研发计划：智能人机交互关键技术与系统（2022-2025）",
    "国家自然科学基金面上项目：基于知识图谱的预训练语言模型研究（2020-2023）",
  ],
  awards: [
    "2024年 国家科技进步二等奖",
    "2022年 教育部自然科学一等奖",
    "2020年 ACM SIGAI中国新星奖",
    "2018年 北京大学优秀教师奖",
  ],
  recruiting_requirements: `1. 具有扎实的数学基础和编程能力（Python/C++）；
2. 对人工智能研究有浓厚兴趣和热情；
3. 良好的英文读写能力；
4. 有科研经历或竞赛获奖经历者优先；
5. 硕士生要求本科GPA排名前20%，博士生要求前10%。`,
  phone: "010-62757801",
  office_address: "北京大学理科一号楼 1234 室",
  source_url: "https://cs.pku.edu.cn/info/zhangsan",
  created_at: "2026-03-15T10:00:00Z",
};

// ========== Mock 用户数据 ==========
export const mockUserProfile: UserProfile = {
  id: 1,
  username: "demo_user",
  email: "demo@example.com",
  avatar_url: null,
  nickname: "保研小助手",
  university: "武汉大学",
  major: "计算机科学与技术",
  grade: "大三",
  bio: "目标 985 计算机方向，加油！",
  gpa_rank: "前 10%",
  target_universities: [
    { university: "北京大学", departments: ["计算机学院", "智能学院"] },
    { university: "清华大学", departments: ["计算机科学与技术系", "人工智能学院"] },
    { university: "浙江大学", departments: ["计算机科学与技术学院"] },
  ],
  research_interests: ["人工智能", "机器学习", "自然语言处理"],
  is_onboarded: true,
  created_at: "2026-01-15T08:00:00Z",
};

export const mockFavorites: FavoriteItem[] = [
  {
    id: 1, type: "notice", target_id: 1,
    title: "2026年计算机科学与技术学院推免夏令营招生通知",
    description: "北京大学 · 计算机科学与技术学院",
    created_at: "2026-03-20T10:30:00Z",
    extra: { university: "北京大学", status: "报名中" },
  },
  {
    id: 2, type: "notice", target_id: 2,
    title: "2026年电子工程系暑期优秀大学生夏令营",
    description: "清华大学 · 电子工程系",
    created_at: "2026-03-22T14:20:00Z",
    extra: { university: "清华大学", status: "报名中" },
  },
  {
    id: 3, type: "school", target_id: 1,
    title: "北京大学",
    description: "985 · 北京 · 48个学院 · 12条通知",
    created_at: "2026-03-18T09:00:00Z",
    extra: { level: "985", province: "北京" },
  },
  {
    id: 4, type: "tutor", target_id: 1,
    title: "张三",
    description: "北京大学 · 计算机科学与技术学院 · 教授/博导",
    created_at: "2026-03-25T16:45:00Z",
    extra: { university: "北京大学", research: "人工智能、机器学习" },
  },
  {
    id: 5, type: "notice", target_id: 4,
    title: "2026年经济学院推免夏令营招生简章",
    description: "复旦大学 · 经济学院",
    created_at: "2026-03-19T11:00:00Z",
    extra: { university: "复旦大学", status: "报名中" },
  },
];

export const mockUserSettings: UserSettings = {
  email_notification: true,
  favorite_update_notification: true,
  deadline_reminder_days: 7,
  interested_disciplines: ["工学", "理学"],
  interested_universities: ["北京大学", "清华大学", "浙江大学"],
};
